# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dimodel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(849, 576)
        Dialog.setStyleSheet("background-image: url(:/bg1.jpg);")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(-20, -10, 891, 601))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 871, 591))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(120, 50, 641, 101))
        self.label.setStyleSheet("color: rgb(56, 99, 7);\n"
"color: rgb(0, 0, 0);\n"
"font: 24pt \"楷体\";")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(320, 230, 251, 61))
        self.pushButton.setStyleSheet("background-image: url(:/bg1.jpg);\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"楷体\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 350, 251, 61))
        self.pushButton_2.setStyleSheet("background-image: url(:/bg1.jpg);\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"楷体\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 470, 251, 61))
        self.pushButton_3.setStyleSheet("background-image: url(:/bg1.jpg);\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"楷体\";")
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "农家乐——果蔬识别与菜品识别系统"))
        self.pushButton.setText(_translate("Dialog", "识别菜品"))
        self.pushButton_2.setText(_translate("Dialog", "查看菜品识别记录"))
        self.pushButton_3.setText(_translate("Dialog", "返回"))
import data.a_rc
