# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frview.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(698, 783)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(-20, -10, 731, 801))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, -20, 731, 821))
        self.label.setStyleSheet("background-image: url(:/bg1.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.tableView = QtWidgets.QTableView(self.frame)
        self.tableView.setGeometry(QtCore.QRect(120, 150, 501, 501))
        self.tableView.setObjectName("tableView")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(270, 690, 171, 51))
        self.pushButton.setStyleSheet("background-image: url(:/bg1.jpg);\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"楷体\";")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(60, 30, 641, 101))
        self.label_3.setStyleSheet("color: rgb(56, 99, 7);\n"
"color: rgb(0, 0, 0);\n"
"font: 24pt \"楷体\";")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "返回"))
        self.label_3.setText(_translate("Dialog", "农家乐——果蔬识别与菜品识别系统"))
import data.a_rc
